---
apiVersion: v2
appVersion: 10.8.1
description: Jellyfin is a Free Software Media System
name: jellyfin
version: 10.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - jellyfin
  - plex
  - emby
home: https://github.com/johanneskastl/helm-charts/tree/main/charts/jellyfin
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-solid-black.svg
sources:
  - https://hub.docker.com/r/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin
maintainers:
  - name: johanneskastl
    email: kastl@b1-systems.de
dependencies:
  - name: common
    repository: https://johanneskastl.github.io/helm-charts/
    version: 5.0.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: generate README with helm-docs
