---
apiVersion: v2
# renovate datasource=docker registryUrl=https://ghcr.io depName=linuxserver/heimdall
appVersion: v2.7.6-ls330
description: An Application dashboard and launcher
name: heimdall
version: 9.4.5
kubeVersion: ">=1.16.0-0"
keywords:
  - heimdall
home: https://github.com/johanneskastl/helm-charts/tree/main/charts/heimdall
icon: https://i.imgur.com/mM4tcO5.png
sources:
  - https://hub.docker.com/r/linuxserver/heimdall/
  - https://github.com/linuxserver/heimdall
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
dependencies:
  - name: common
    repository: https://johanneskastl.github.io/helm-charts/
    version: 5.0.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update heimdall to v2.7.6-ls330
