---
apiVersion: v2
appVersion: v1.90.6
# renovate datasource=docker registryUrl=docker.io depName=tailscale/tailscale
description: Run a tailscale subnet router in Kubernetes
name: tailscale
version: 0.32.1
kubeVersion: ">=1.19.0-0"
keywords:
  - tailscale
  - vpn
  - wireguard
home: https://github.com/johanneskastl/helm-charts/tree/main/charts/tailscale
sources:
  - https://github.com/tailscale/tailscale
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
dependencies:
  - name: common
    repository: https://johanneskastl.github.io/helm-charts/
    version: 5.0.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: adapt README to new name 'authkey' for environment variable
    - kind: added
      description: comment in Chart.yaml to allow updates via Renovatebot
