---
apiVersion: v2
# renovate datasource=docker registryUrl=https://docker.io depName=eikek0/sharry
appVersion: v1.15.0
description: Sharry allows to share files with others in a simple way. It is a self-hosted web application. The basic concept is to upload files and get a url back that can then be shared.
name: sharry
version: 6.9.2
keywords:
  - file sharing
home: https://github.com/johanneskastl/charts/tree/main/charts/sharry
icon: https://github.com/eikek/sharry/blob/master/artwork/logo.svg?raw=true
sources:
  - https://github.com/eikek/sharry
  - https://hub.docker.com/r/eikek0/sharry
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
dependencies:
  - name: common
    repository: https://johanneskastl.github.io/helm-charts/
    version: 5.0.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: add https prefix in renovate comment
