---
apiVersion: v2
# renovate datasource=docker registryUrl=https://docker.io depName=389ds/dirsrv
appVersion: '2.2'
description: 389ds LDAP server
name: 389ds
version: 0.0.3
kubeVersion: ">=1.19.0-0"
keywords:
  - 389-ds
  - 389ds
  - dirsrv
  - LDAP
home: https://github.com/johanneskastl/helm-charts/tree/main/charts/389ds
icon: https://www.port389.org/images/logo-header-transparent.png
sources:
  - https://github.com/389ds/389-ds-base/
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
dependencies:
  - name: common
    repository: https://johanneskastl.github.io/helm-charts/
    version: 5.0.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: add https prefix to renovate comment
