---
apiVersion: v2
# renovate datasource=docker registryUrl=https://docker.io depName=louislam/uptime-kuma
appVersion: 2.1.0
description: A fancy self-hosted monitoring tool for your websites and applications
name: uptime-kuma
version: 3.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - uptime-kuma
  - status
  - status-page
  - monitoring
home: https://github.com/johanneskastl/helm-charts/tree/main/charts/uptime-kuma
icon: https://github.com/louislam/uptime-kuma/raw/master/public/icon.svg
sources:
  - https://github.com/louislam/uptime-kuma
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
dependencies:
  - name: common
    repository: https://johanneskastl.github.io/helm-charts/
    version: 5.0.5
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update uptime-kuma to 2.1.0
