---
name: "Charts: Lint and test"

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!charts/**/README.md'
      - '!charts/**/README.md.gotmpl'
  pull_request:
    paths:
      - 'charts/**'
      - '!charts/**/README.md'
      - '!charts/**/README.md.gotmpl'

permissions: {}

jobs:
  lint-test:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4  # v4.3.1

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.14'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f  # v2.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${REPOSITORY_DEFAULT_BRANCH})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${REPOSITORY_DEFAULT_BRANCH}
        env:
          REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
